#!/bin/bash

ASSEMBLED="tmp.o"

### Assemble ###

nasm -f elf64 "$1" -o $ASSEMBLED

if ! [ $? -eq 0 ]; then
    exit $?
fi

### Link ###

ld $ASSEMBLED

if ! [ $? -eq 0 ]; then
    echo "Linking failed"
    exit $?
fi

rm $ASSEMBLED

### Run ###

./a.out