#!/bin/bash


### Assemble ###

nasm -f elf64 "$1" -o tmp.o

if ! [ $? -eq 0 ]; then
    exit $?
fi

### Link ###

ld tmp.o

if ! [ $? -eq 0 ]; then
    echo "Linking failed"
    exit $?
fi

### Run ###

./a.out